"""auditoria de costo

Revision ID: 4c5269917b66
Revises: 585877974ab1
Create Date: 2026-07-30 14:12:25.652163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5269917b66'
down_revision: Union[str, Sequence[str], None] = '585877974ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_costo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('linea_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('costo_usd_usado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('columna_origen', sa.String(length=4), nullable=True),
    sa.Column('leido_en', sa.DateTime(), nullable=False),
    sa.Column('calculo_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_costo_calculo_id'), 'auditoria_costo', ['calculo_id'], unique=False)
    op.create_index(op.f('ix_auditoria_costo_linea_id'), 'auditoria_costo', ['linea_id'], unique=False)
    op.create_index(op.f('ix_auditoria_costo_sku'), 'auditoria_costo', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_costo_sku'), table_name='auditoria_costo')
    op.drop_index(op.f('ix_auditoria_costo_linea_id'), table_name='auditoria_costo')
    op.drop_index(op.f('ix_auditoria_costo_calculo_id'), table_name='auditoria_costo')
    op.drop_table('auditoria_costo')
    # ### end Alembic commands ###
