"""modelo inicial

Revision ID: e6c8a4276be2
Revises: 
Create Date: 2026-07-29 20:10:52.800713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c8a4276be2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro_tasa',
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('motor', sa.String(length=16), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('prefijo_perdida_definitiva',
    sa.Column('prefijo', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('prefijo')
    )
    op.create_table('regimen_comprobante',
    sa.Column('comprobante', sa.String(length=10), nullable=False),
    sa.Column('regimen', sa.Enum('CUENTA_1', 'CUENTA_2', 'PERDIDA_DEFINITIVA', 'EXCLUIDO', 'NO_DETERMINADO', 'NO_RECONOCIDO', name='regimen'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('comprobante')
    )
    op.create_table('sku_auxiliar',
    sa.Column('patron', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('patron')
    )
    op.create_table('sku_excluido',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('motivo', sa.Enum('NOTA_DEBITO', 'FIXTURE', 'ENVIO', 'SKU_AUXILIAR', 'MANUAL', name='motivoexclusion'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('venta_ecom',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('periodo', sa.String(length=64), nullable=False),
    sa.Column('excluido', sa.Boolean(), nullable=False),
    sa.Column('motivo_exclusion', sa.Enum('NOTA_DEBITO', 'FIXTURE', 'ENVIO', 'SKU_AUXILIAR', 'MANUAL', name='motivoexclusion'), nullable=True),
    sa.Column('numero_orden', sa.String(length=64), nullable=False),
    sa.Column('skus_vendidos', sa.String(length=1000), nullable=False),
    sa.Column('fecha_creacion_venta', sa.Date(), nullable=True),
    sa.Column('estado_venta', sa.String(length=32), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('estado_pago', sa.String(length=32), nullable=True),
    sa.Column('costo_sin_iva', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('iva_a_favor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('canal_de_venta', sa.String(length=64), nullable=True),
    sa.Column('usuario_integracion', sa.String(length=255), nullable=True),
    sa.Column('medio_de_cobro', sa.String(length=255), nullable=True),
    sa.Column('entrega_envio', sa.String(length=255), nullable=True),
    sa.Column('comision_venta', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('comision_cobro', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('impuestos_informados', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('precio_sin_iva', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('imp_cheque', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iibb', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('precio_final', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('dif_iva', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cash', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('utilidad_venta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('utilidad_costo', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('neto', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('costo_total', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rentabilidad', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pm', sa.String(length=100), nullable=True),
    sa.Column('subcategoria', sa.String(length=255), nullable=True),
    sa.Column('rentabilidad_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('facturacion_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('responsable_de_ventas', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('subcategoria2', sa.String(length=255), nullable=True),
    sa.Column('periodo_excel', sa.String(length=64), nullable=True),
    sa.Column('semana', sa.String(length=64), nullable=True),
    sa.Column('sku_negativo', sa.String(length=32), nullable=True),
    sa.Column('tc', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('vinculacion', sa.String(length=32), nullable=False),
    sa.Column('iva', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('facturacion_iva', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ventas_30_dias', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('dias_de_stock', sa.String(length=32), nullable=True),
    sa.Column('precio_de_venta_roto', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rentabilidad_real', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pct_rentabilidad', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_ecom_numero_orden'), 'venta_ecom', ['numero_orden'], unique=True)
    op.create_index(op.f('ix_venta_ecom_periodo'), 'venta_ecom', ['periodo'], unique=False)
    op.create_table('venta_tactica',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('periodo', sa.String(length=64), nullable=False),
    sa.Column('excluido', sa.Boolean(), nullable=False),
    sa.Column('motivo_exclusion', sa.Enum('NOTA_DEBITO', 'FIXTURE', 'ENVIO', 'SKU_AUXILIAR', 'MANUAL', name='motivoexclusion'), nullable=True),
    sa.Column('regimen', sa.Enum('CUENTA_1', 'CUENTA_2', 'PERDIDA_DEFINITIVA', 'EXCLUIDO', 'NO_DETERMINADO', 'NO_RECONOCIDO', name='regimen'), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('fabricante', sa.String(length=255), nullable=True),
    sa.Column('tipo_producto', sa.String(length=100), nullable=True),
    sa.Column('familia', sa.String(length=255), nullable=True),
    sa.Column('vendedor', sa.String(length=255), nullable=True),
    sa.Column('tipo_factura', sa.String(length=10), nullable=False),
    sa.Column('nro_factura', sa.String(length=32), nullable=False),
    sa.Column('precio_compra_lista', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('costo_lista', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('precio_venta_lista', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('costo_total_dolares', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('iva_producto', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('margen_informado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iva', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('imp_cheque', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iibb', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tc', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('costo_total_pesos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('margen_x', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('costo_financiero_1', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('costo_financiero_2', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('margen_real', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('margen_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sku_margen_negativo', sa.String(length=32), nullable=True),
    sa.Column('pm', sa.String(length=100), nullable=True),
    sa.Column('canal_tactica', sa.String(length=32), nullable=False),
    sa.Column('subcategoria', sa.String(length=255), nullable=True),
    sa.Column('precio_venta_iva', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('margen_l3', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('margen_l4', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('margen_l5', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_factura', 'codigo', name='uq_venta_tactica_comprobante_sku')
    )
    op.create_index(op.f('ix_venta_tactica_codigo'), 'venta_tactica', ['codigo'], unique=False)
    op.create_index(op.f('ix_venta_tactica_periodo'), 'venta_tactica', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_tactica_periodo'), table_name='venta_tactica')
    op.drop_index(op.f('ix_venta_tactica_codigo'), table_name='venta_tactica')
    op.drop_table('venta_tactica')
    op.drop_index(op.f('ix_venta_ecom_periodo'), table_name='venta_ecom')
    op.drop_index(op.f('ix_venta_ecom_numero_orden'), table_name='venta_ecom')
    op.drop_table('venta_ecom')
    op.drop_table('sku_excluido')
    op.drop_table('sku_auxiliar')
    op.drop_table('regimen_comprobante')
    op.drop_table('prefijo_perdida_definitiva')
    op.drop_table('parametro_tasa')
    # ### end Alembic commands ###
